#SPDX-License-Identifier: MIT-0
galaxy_info:
  author: Setor de Tecnologia de Informação
  description: Configura estação de trabalho com Debian KDE
  company: Câmara Municipal de Tapira - MG

  license: license (GPL-2.0-or-later, MIT, etc)

  min_ansible_version: 2.1

  platforms:
    - name: Debian
      versions:
      - trixie

  galaxy_tags:
    - cmtapira
    - estacaodetrabalho


dependencies: []
